site:
  title: What Makes Ansible Automation Platform 2.5 Better Than 2.4?

  start_page: difference_AAP2.4_AAP2.5::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
