= Types of Installation: 

Starting with Ansible Automation Platform 2.5, three different on-premise deployment models are fully tested. In addition to the older existing RPM-based installer and operator which was there for Ansible Automation Platform 2.4, now with Ansible Automation Platform 2.5 the containerized installer is being added  	

As the platform moves toward a container-first model, the RPM-based installer will be removed in a future release		

|===
|RPM | Containerized | Openshift Operator
| Suitable for traditional RHEL environments

Deprecated with AAP 2.5 (removal TBD)|Ideal for flexibility and rapid scaling

Simplifies dependency management
 | Seamless integration with Openshift

Automated lifecycle management
|===

System Requirement 

Since the Container and Operator based deployment needs 3000 IOPS (input/output operations per second) compared to the VM bases Deployment 1500 IOPS please refer to the below Guides while doing the deployment: 

RPM : The https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/rpm_installation/platform-system-requirements[System requirements] section of RPM installation. 			

Containerized : The https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/containerized_installation/aap-containerized-installation#system_requirements[System requirements] section of Containerized installation. 			

For https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/tested_deployment_models/ocp-topologies#tested_system_configurations_6[system requirements] for installing Ansible Automation Platform on OpenShift Container Platform, see the Tested system configurations section of Tested deployment models. 


*Containerized Deployment*

From Ansible Automation platform Containerized Deployment is fully Supported Deployment which use the power of the RHEL + Podman. Containerized Ansible Automation Platform runs the component services as podman based containers on top of a RHEL host.  This helps many customers to utilize the benefits of Container with Ansible Automation Platform together. 

Containerized Ansible Automation Platform is the first step towards a more streamlined and improved platform management experience, incorporating our future vision and strategy.

The benifits of using *AAP* on Containers: 

- *Simplified Installation*: Users can now access the installation procedure more easily thanks to its simplification.
- *Integration*: It utilize technology that ensures a more integrated, richer experience for both initial and ongoing management.
- *Enhanced Security*: Installation can be done as non-root user with privilege escalation ( user mapped to rootless podman namespace).
- *Future Feature Platform*: The containerized platform lays the groundwork for upcoming improvements.
- *Lighter Footprint*: It ensures optimal performance by serving a variety of markets and solutions.
- *Config as code*: YAML-like controller configuration can be used to provide a pre seeded information to the automation controller during the time of deployment. 
- *Uninstallation*: Remove the Ansible Automation Platform setup using scripts.

